SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [ods].[transacciones]
AS
BEGIN



  INSERT INTO ods.TRANSACCION (FUENTE,
  DNI,
  RUC,
  FECHA,
  HORA,
  RAZONSOCIAL,
  RUCEMISOR,
  NOMBRETIENDA,
  UBICACION,
  CODIGOTIENDA_SRV,
  CODIGOPRODUCTO_SRV,
  DESCRIPCIONPRODUCTO,
  CANTIDADUNIDADESITEM,
  PRECIOVENTAUNITARIOITEM,
  CARGODESCUENTOITEM,
  PRECIOTOTALITEM,
  TOTALVALORVENTANETA,
  MONTOTOTALIGV,
  DESCUENTOSGLOBAL,
  TOTALVALORVENTABRUTA,
  MONEDA)
    SELECT
      'SRV'
     ,DNI
     ,RUC
     ,FECHA
     ,HORA
     ,RAZONSOCIAL
     ,RUCEMISOR
     ,NOMBRETIENDA
     ,CODIGOMALL
     ,CODIGOTIENDA
     ,CODIGOPRODUCTO
     ,DESCRIPCIONPRODUCTO
     ,CONVERT(FLOAT, CANTIDADUNIDADESITEM)
     ,CONVERT(FLOAT, PRECIOVENTAUNITARIOITEM)
     ,CONVERT(FLOAT, CARGODESCUENTOITEM)
     ,CONVERT(FLOAT, PRECIOTOTALITEM)
     ,CONVERT(FLOAT, TOTALVALORVENTANETA)
     ,CONVERT(FLOAT, MONTOTOTALIGV)
     ,CONVERT(FLOAT, DESCUENTOSGLOBAL)
     ,CONVERT(FLOAT, TOTALVALORVENTABRUTA)
     ,MONEDA
    FROM stg.TABLON_SRV;

  INSERT INTO ods.TRANSACCION (FUENTE,
  DNI,
  RUC,
  COD_CLIENTE_ICG,
  FECHA,
  NEGOCIO,
  NOMBRETIENDA,
  UBICACION,
  CODIGOCENTRO_ICG,
  CODARTICULO_ICG,
  DESCRIPCIONPRODUCTO,
  CANTIDADUNIDADESITEM,
  PRECIOTOTALITEM,
  TOTALVALORVENTANETA,
  MONTOTOTALIGV,
  TOTALVALORVENTABRUTA,
  MONEDA)
    SELECT
      'ICG'
     ,IIF(LEN(c.cif) = 8, c.cif, NULL) AS d
     ,IIF(LEN(c.cif) = 11, c.cif, NULL) AS r
     ,t.COD_CLIENTE
     ,t.FECHA
     ,t.NEGOCIO
     ,t.NOM_TIENDA
     ,t.UBICACION
     ,t.centro
     ,t.CODARTICULO
     ,ai.DESCRIPCION
     ,t.UNIDADESTOTAL
     ,t.TOTAL_L
     ,t.BASE
     ,t.IMPUESTO
     ,t.TOTAL
     ,'PEN' AS m
    FROM stg.TRANSACCION_ICG AS t
    INNER JOIN stg.CLI_ICG AS c
      ON c.COD_EMPRESA = t.COD_EMPRESA
        AND c.COD_CLIENTE = t.COD_CLIENTE
    LEFT JOIN stg.ARTICULOS_ICG AS ai
      ON ai.COD_EMPRESA = t.COD_EMPRESA
        AND ai.CODARTICULO = t.CODARTICULO
    WHERE t.TVENTA = 'BASE'
    AND LEN(c.cif) = 8
    OR LEN(c.cif) = 11;

  INSERT INTO ods.TRANSACCION (FUENTE,
  DNI,
  RUC,
  NUMTARJETABONUS,
  FECHA,
  HORA,
  NOMBRETIENDA,
  UBICACION,
  CODIGOTIENDA_BONUS,
  PLU_BONUS,
  CANTIDADUNIDADESITEM,
  PRECIOTOTALITEM,
  TOTALVALORVENTABRUTA,
  MONEDA)
    SELECT
      'LYTY'
     ,c.NRODOCUMENTO
     ,c.NRORUC
     ,t.NUMTARJETABONUS
     ,t.FECHATRANSACCION_CAB
     ,t.HORATRANSACCION_CAB
     ,ll.DESCRIPCIONTDA --t.CODIGODELOCAL 
     ,al.RE_UNDECO  --t.CODIGODEPARTICIPANTE
     ,t.CODIGODEPARTICIPANTE
     ,t.PLU
     ,t.CANTIDADNUM
     ,t.MONTOPARCIALNUM
     ,t.MONTOTOTALNUM
     ,'PEN'
    FROM stg.TRANSACCION_LYTY AS t
    INNER JOIN stg.CLI_LYTY AS c
      ON c.NUMTARJETABONUS = t.NUMTARJETABONUS
    INNER JOIN stg.ASOCIADO_LYTY al
      ON t.CODIGODEPARTICIPANTE = al.ASOCIADO
    INNER JOIN stg.LOCATARIO_LYTY ll
      ON t.CODIGODEPARTICIPANTE = ll.ASOCIADO
     AND t.CODIGODELOCAL = ll.LOCATARIO
END;
GO