SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [ods].[maestroClientes]
AS
BEGIN


SELECT DISTINCT DNI, RUC, NOMBRECLIENTE, DIRECCIONCLIENTE, BONUS
  INTO ods.CLI_SRV
FROM stg.TABLON_SRV
;


INSERT INTO ods.CLIENTE(
FUENTE,
NUMTARJETABONUS    ,
TIPOTARJETA        ,
ORDTARJETABONUS    ,
CODIGOTIPOPERSONA  ,
CODIGOTIPOPERSONA_D,
TIPODEDOCUMENTO    ,
TIPODEDOCUMENTO_D  ,
RUC                ,
NRODOCUMENTO       ,
RAZONSOCIAL_BONUS  ,
APELLIDOPATERNO    ,
APELLIDOMATERNO    ,
NOMBRES            ,
FECHANACIMIENTO_S  ,
DIRECCION1         ,
REFERENCIA         ,
DISTRITO           ,
PROVINCIA          ,
DEPARTAMENTO       ,
LATITUD            ,
LONGITUD           ,
TELEFONO1          ,
TELEFONO_D         ,
HIJ_AS             ,
HIJ_OS             ,
HIJ_NN             ,
HIJ_TOT            ,
NIVELSOCIOECONOMICO,
COD_SUBR_FUENTE)
SELECT
'LYTY',
NUMTARJETABONUS      ,
TIPOTARJETA          ,
ORDTARJETABONUS      ,
CODIGOTIPOPERSONA    ,
CODIGOTIPOPERSONA_D  ,
TIPODEDOCUMENTO      ,
TIPODEDOCUMENTO_D    ,
NRORUC               ,
NRODOCUMENTO         ,
RAZONSOCIAL          ,
APELLIDOPATERNO      ,
APELLIDOMATERNO      ,
NOMBRES              ,
FECHANACIMIENTO      ,
DIRECCION            ,
REFERENCIA           ,
DISTRITO             ,
PROVINCIA            ,
DEPARTAMENTO         ,
COORDENADAX          ,
COORDENADAY          ,
TELEFONO             ,
TELEFONO_D           ,
HIJ_AS               ,
HIJ_OS               ,
HIJ_NN               ,
HIJ_TOT              ,
NSE                  ,
CODIGOPERSONA
FROM stg.CLI_LYTY
;


INSERT INTO ods.CLIENTE(
FUENTE,
NRODOCUMENTO       ,
NOMBRECOMERCIAL_ICG,
NOMBRECLIENTE      ,
DIRECCION1         ,
POBLACION          ,
PROVINCIA          ,
PAIS               ,
CODPOSTAL          ,
TELEFONO1          ,
TELEFONO2          ,
CORREO             ,
ALIAS              ,
PERSONACONTACTO    ,
CODCONTABLE        ,
COD_SUBR_FUENTE    ,
COD_EMPRESA_DMVTAS
)
SELECT
'ICG',
CIF            ,
NOMBRECOMERCIAL,
NOMBRECLIENTE  ,
DIRECCION1     ,
POBLACION      ,
PROVINCIA      ,
PAIS           ,
CODPOSTAL      ,
TELEFONO1      ,
TELEFONO2      ,
E_MAIL         ,
ALIAS          ,
PERSONACONTACTO,
CODCONTABLE    ,
COD_CLIENTE,
COD_EMPRESA
FROM stg.CLI_ICG
;


INSERT INTO ods.CLIENTE(
FUENTE,
NUMTARJETABONUS  ,
RUC              ,
NRODOCUMENTO     ,
NOMBRECLIENTE_SRV,
DIRECCION1
)
SELECT
'SRV',
BONUS        ,
RUC          ,
DNI          ,
NOMBRECLIENTE,
DIRECCIONCLIENTE
FROM ods.CLI_SRV
;


INSERT INTO ods.CLIENTE(
FUENTE,
NRODOCUMENTO     ,
APELLIDOS        ,
NOMBRES          ,
NOMBRECLIENTE    ,
FECHANACIMIENTO_D,
SEXO             ,
DIRECCION1       ,
DISTRITO         ,
TELEFONO1        ,
CORREO           ,
NIVELSOCIOECONOMICO
)
SELECT
'MKT',
DOCUMENTOIDENTIFICACION,
APELLIDOS              ,
NOMBRE                 ,
NOMBRECOMPLETO         ,
FECHANACIMIENTO        ,
SEXO                   ,
DIRECCION              ,
DISTRITO               ,
TELEFONO               ,
CORREO                 ,
NIVELSOCIOECONOMICO
FROM stg.CLI_MKT
;

END;
GO