CREATE TABLE [stg].[WAPP_C_MD] (
  [LOCATION] [varchar](50) NULL,
  [TIPO_DE_CUENA] [varchar](50) NULL,
  [TIPO_DE_PERSONA] [varchar](50) NULL,
  [TIPO_DE_USUARIO] [varchar](50) NULL,
  [USA_CANAL] [varchar](50) NULL,
  [VALIDA_SALDO_EN_CANAL] [varchar](50) NULL,
  [MOBILE_NUMBER] [varchar](50) NULL,
  [TYPE_OF_DOCUMENT] [varchar](50) NULL,
  [DOCUMENT_NUMBER] [varchar](50) NULL,
  [TRANSACTION_ID] [varchar](50) NULL,
  [DATE] [varchar](50) NULL,
  [TIME] [varchar](50) NULL,
  [CURRENCY] [varchar](50) NULL,
  [AMOUNT] [varchar](50) NULL,
  [TRANSACTION_TYPE] [varchar](50) NULL,
  [COMMISSION] [varchar](50) NULL,
  [SERVICE_CHARGE] [varchar](50) NULL,
  [USER_TYPE] [varchar](50) NULL,
  [USER_ID] [varchar](50) NULL,
  [DESTINATION_MOBILE] [varchar](50) NULL,
  [MERCHANT_CODE] [varchar](50) NULL,
  [BILL_ID] [varchar](50) NULL,
  [SERVICE_ID] [varchar](50) NULL,
  [BILL_CATEGORY] [varchar](50) NULL,
  [CUPON_CODIGO_PROMOCIONAL] [varchar](50) NULL,
  [TIPO_DE_BILLETERA] [varchar](50) NULL
)
ON [PRIMARY]
GO