CREATE TABLE [stg].[xSRV_TABLON_old] (
  [ID] [varchar](30) NULL,
  [NOMBRE] [varchar](50) NULL,
  [RAZONSOCIAL] [varchar](50) NULL,
  [NOMBRETIENDA] [varchar](50) NULL,
  [CODIGOMALL] [varchar](2) NULL,
  [CODIGOTIENDA] [varchar](4) NULL,
  [RUCEMISOR] [varchar](11) NULL,
  [IDENTIFICADORTERMINAL] [varchar](10) NULL,
  [NUMEROTERMINAL] [varchar](10) NULL,
  [SERIE] [varchar](10) NULL,
  [TIPOTRANSACCION] [varchar](4) NULL,
  [NUMEROTRANSACCION] [varchar](10) NULL,
  [FECHA] [varchar](20) NULL,
  [HORA] [varchar](20) NULL,
  [CAJERO] [varchar](20) NULL,
  [VENDEDOR] [varchar](20) NULL,
  [DNI] [varchar](11) NULL,
  [RUC] [varchar](11) NULL,
  [NOMBRECLIENTE] [varchar](100) NULL,
  [DIRECCIONCLIENTE] [varchar](200) NULL,
  [BONUS] [varchar](20) NULL,
  [MONEDA] [varchar](10) NULL,
  [MEDIOPAGO] [varchar](10) NULL,
  [TOTALVALORVENTABRUTA] [varchar](20) NULL,
  [DESCUENTOSGLOBAL] [varchar](20) NULL,
  [MONTOTOTALIGV] [varchar](20) NULL,
  [TOTALVALORVENTANETA] [varchar](20) NULL,
  [ORDENITEM] [varchar](20) NULL,
  [CANTIDADUNIDADESITEM] [varchar](20) NULL,
  [CODIGOPRODUCTO] [varchar](50) NULL,
  [DESCRIPCIONPRODUCTO] [varchar](100) NULL,
  [PRECIOVENTAUNITARIOITEM] [varchar](20) NULL,
  [CARGODESCUENTOITEM] [varchar](20) NULL,
  [PRECIOTOTALITEM] [varchar](20) NULL
)
ON [PRIMARY]
GO